title = 'Apuntes ETSII UMA'
theme = 'hugo-book'
relativeURLs = true
languageCode = 'es'
enableGitInfo = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

[markup.goldmark.renderer]
 unsafe = true

[params]
  BookTheme = 'dark'
  BookLogo = 'logo.svg'
  BookRepo = 'https://github.com/pablouser1/apuntes-etsii-uma'
